config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDevise設定
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用のDevise設定
  devise_for :enduser, controllers: {
    registrations: "enduser/registrations",
    sessions: 'enduser/sessions'
  }
  devise_scope :enduser do
  post 'users/guest_sign_in', to: 'enduser/sessions#guest_sign_in'
  end

  scope module: :enduser do
    root to: 'homes#top' # ルートパスを設定
    get 'about' => "homes#about"
    resources :favorite, only: [:create, :destroy]
    get 'users/confirm_withdrawal'
    patch 'users/withdrawal'
    get 'users/participant'
    get '/post/hashtag/:name', to: "posts#hashtag"
    resources :posts do
      resources :participants
    end
    resources :calendars
    resources :users do
      member do
        get 'favorite_users', to: 'users#favorite_users'
      end
      resource :relationships, only: [:show ,:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
          get 'followingspost' => 'relationships#followingspost'
    end
    get "search" => "searches#search"

  end

  namespace :admin do
    root to: 'homes#top'
    get "" => "homes#top"
    resources :posts
    resources :tags#, only: [:index, :create, :edit, :update]
    resources :endusers
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :tag_title, presence: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @tag = Tag.new
  end

  def index
    @tag = Tag.new
    @admin_tags = Tag.all # 例: すべてのタグを取得して @admin_tags に代入
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
    @admin_tags = Tag.all
    @tag.save
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      render :edit
    end
  end
  def destroy
    @tag = Tag.find(params[:id])
    @admin_tags = Tag.all
    @tag.destroy
    # redirect_to admin_tags_path, notice: 'タグが削除されました'
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_title)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_tag_list.html.erb
 <ul class="list-group mt-3">
    <% admin_tags.each do |tag| %>
      <li class="list-group-item">
        <%= tag.tag_title %>
        <span class="float-right">
          <%= link_to "編集", edit_admin_tag_path(tag), local: true ,class: "btn btn-secondary btn-sm mr-2" %>
          <%= link_to "削除", admin_tag_path(tag), method: :delete, remote: true ,data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm" %>
        </span>
      </li>
    <% end %>
  </ul>

app/views/admin/tags/_tag_new.html.erb
<%= form_with model: tag, url: admin_tags_path, local: false do |form| %>
  <div class="form-group">
    <%= form.label :tag_title %>
    <%= form.text_field :tag_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "タグを新規作成", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/tags/create.js.erb
$("#tag_lists").html("<%= j(render 'tag_list',admin_tags: @admin_tags) %>");
$("#tag_new").html("<%= j(render 'tag_new',tag: @tag) %>");

app/views/admin/tags/destroy.js.erb
$("#tag_lists").html("<%= j(render 'tag_list', admin_tags: @admin_tags) %>");
$("#tag_new").html("<%= j(render 'tag_new',tag: @tag) %>");

app/views/admin/tags/edit.html.erb
<div class="card-container">
    <div class="card-body">
      <h1 class="card-title">タグ編集</h1>

      <%= form_with model: @tag, url: admin_tag_path(@tag), method: :patch, local: true do |form| %>
        <div class="field">
          <%= form.label :タグ名%>
          <%= form.text_field :tag_title, class: "form-control" %>
        </div>

        <div class="actions mt-4">
          <%= form.submit "編集", class: "btn btn-primary" %>

          <%= link_to "削除", admin_tag_path(@tag), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<style>
  .card-container {
  background-color: rgba(255, 255, 255, 0.8); /* 半透明の白色の背景 */
  max-width: 400px; /* 必要に応じて最大幅を調整 */
  margin: 0 auto; /* カードを中央に配置 */
  padding: 20px; /* カード内の余白を追加 */
  border-radius: 10px; /* 角を丸める */
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 微かな影を追加 */
}
</style>

app/views/admin/tags/index.html.erb
<div class="container mt-5">
  <h1>タグの新規作成</h1>
  <div id="tag_new">
    <%= render 'tag_new',tag: @tag %>
  </div>
</div>

<div class="container mt-5">
  <h1>タグ一覧</h1>
  <div id="tag_lists">
    <%= render 'tag_list',admin_tags: @admin_tags %>
  </div>
</div>

app/views/admin/tags/update.html.erb
<h1>Admin::Tags#update</h1>
<p>Find me in app/views/admin/tags/update.html.erb</p>