config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDevise設定
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用のDevise設定
  devise_for :enduser, controllers: {
    registrations: "enduser/registrations",
    sessions: 'enduser/sessions'
  }
  devise_scope :enduser do
  post 'users/guest_sign_in', to: 'enduser/sessions#guest_sign_in'
  end

  scope module: :enduser do
    root to: 'homes#top' # ルートパスを設定
    get 'about' => "homes#about"
    resources :favorite, only: [:create, :destroy]
    get 'users/confirm_withdrawal'
    patch 'users/withdrawal'
    get 'users/participant'
    get '/post/hashtag/:name', to: "posts#hashtag"
    resources :posts do
      resources :participants
    end
    resources :calendars
    resources :users do
      member do
        get 'favorite_users', to: 'users#favorite_users'
      end
      resource :relationships, only: [:show ,:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
          get 'followingspost' => 'relationships#followingspost'
    end
    get "search" => "searches#search"

  end

  namespace :admin do
    root to: 'homes#top'
    get "" => "homes#top"
    resources :posts
    resources :tags#, only: [:index, :create, :edit, :update]
    resources :endusers
  end

end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_one_attached :profile_picture
  has_many :followings, -> { where(is_deleted: false) }, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, -> { where(is_deleted: false) }, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :posts, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :calendars, dependent: :destroy
  attr_accessor :custom_playlist_name
  attr_accessor :custom_wantlist_name

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :encrypted_password, presence: true, length: { minimum: 6 }, confirmation: true

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |enduser|
      enduser.password = SecureRandom.urlsafe_base64
      enduser.name = 'Guest User'  # デフォルトの名前を設定
      # 他のゲストユーザーの属性をここに追加する
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def participate!(post)
    participants.create(post: post)
  end

  def participant_for(post)
    participants.find_by(post_id: post.id)
  end

  def guest?
  name == "Guest User"
  end

  def self.search_for(content, method)
      Enduser.where('name LIKE ?', '%' + content + '%')
  end

     # フォローしたときの処理
  def follow(enduser_id)
    relationships.create(followed_id: enduser_id)
  end
  # フォローを外すときの処理
  def unfollow(enduser_id)
    relationships.find_by(followed_id: enduser_id).destroy
  end
  # フォローしているか判定
  def following?(enduser)
    followings.include?(enduser)
  end

end

app/controllers/admin/endusers_controller.rb
class Admin::EndusersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = Enduser.all
  end

  def show
    @enduser = Enduser.find(params[:id])
    @favorites = @enduser.favorites
    @playlist = @enduser.playlist
    @wantlist = @enduser.wantlist
    @calendars = @enduser.calendars
    @calendar = Calendar.new
  end

  def edit
    @enduser = Enduser.find(params[:id])
  end

  def update
    @enduser = Enduser.find(params[:id])
      if @enduser.update(enduser_params)
        redirect_to admin_endusers_path
      else
        render :edit
      end
  end

  private
  def enduser_params
    params.require(:enduser).permit(:name, :bio, :playlist, :wantlist, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/enduser/calendars_controller.rb
class Enduser::CalendarsController < ApplicationController

  def index

  end

  def show
    # @calendar = current_enduser.calendars.find(params[:id])
    @calendar = Calendar.find(params[:id])
    pp "@calendar--------------------------#{@calendar.inspect}"
  end

  def new
    @calendars = current_user.calendars
  end

  def edit
    @calendar = current_enduser.calendars.find(params[:id])
  end

  def update

    @calendar = current_enduser.calendars.find(params[:id])
    @calendar.update(update_params)
    redirect_to user_path(current_enduser)
  end

  def create
    @calendar = current_enduser.calendars.new(calendar_memo)
    if @calendar.save
      redirect_to user_path(current_enduser)
    else
      redirect_to new_calendar_path
    end
  end

  def destroy
    @calendars = current_enduser.calendars.find(params[:id])
    @calendars.destroy
    redirect_to user_path(current_enduser)
  end


  private
  def calendar_memo
    params.require(:calendar).permit(:start_time,:title, :content)
  end

  def user
    @user = Enduser.find(params[:id])
  end

  def update_params
    params.require(:calendar).permit(:start_time,:title, :content,:user_id)
  end
end

app/controllers/enduser/confirmations_controller.rb
# frozen_string_literal: true

class Enduser::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_enduser!
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/enduser/favorite_controller.rb
class Enduser::FavoriteController < ApplicationController
  before_action :authenticate_enduser!
  def create
  end

  def destroy
  end
end

app/controllers/enduser/homes_controller.rb
class Enduser::HomesController < ApplicationController
  def top
    @hide_header = true
    render :layout => 'application_top'
  end
  def about
    render :layout => 'application_about'
  end
end

app/controllers/enduser/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Enduser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_enduser!
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/enduser/participants_controller.rb
class Enduser::ParticipantsController < ApplicationController
  before_action :authenticate_access
  def index
    @post = Post.find(params[:post_id])
  end

  def create
    puts "Post ID from params: #{params[:post_id]}"
    @post = Post.find(params[:post_id])
    #byebug
    current_enduser.participate!(@post)
    redirect_to post_participants_path, notice: '参加しました。'
  end

  def destroy
    @post = Post.find(params[:post_id])
    participant = current_enduser.participant_for(@post)
    participant.destroy if participant

    redirect_to post_participants_path, notice: '参加を取り消しました。'
  end

  def show
  end

private
  def authenticate_access
    unless current_admin || current_enduser
      redirect_to new_enduser_session_path, alert: "管理者またはアドミンとしてログインが必要です"
    end
  end
end

app/controllers/enduser/passwords_controller.rb
# frozen_string_literal: true

class Enduser::PasswordsController < Devise::PasswordsController
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/enduser/posts_controller.rb
class Enduser::PostsController < ApplicationController
  before_action :authenticate_enduser!
  def new
    if current_enduser
      @post = current_enduser.posts.new
    else
      redirect_to new_enduser_session_path, alert: "ログインが必要です"
    end
  end

  def index
    @tags = Tag.all # タグを取得

    if params[:enduser_id].present?
      @user = Enduser.find(params[:enduser_id])
      # 特定のユーザーに関連する投稿を取得
      @user_posts = @user.posts.includes(:hashtags, :tag)
    else
      # 全ての投稿を取得
      @user_posts = Post.includes(:hashtags, :tag)
      @posts = Post.all.page(params[:page]).per(4)
    end

  end

  def create
    @post = current_enduser.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: '投稿が作成されました。'
    else
       @tags = Tag.all
        flash.now[:alert] = '投稿にエラーがあります。'
        render :new # new.html.erbを表示します
    end
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path, notice: '投稿が削除されました。'
  end

  def show
    @post = Post.find(params[:id])
    @tag = Tag.find(@post.tag_id)
  end

  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @posts = @tag.posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :body, :tag_id)
  end
end

app/controllers/enduser/registrations_controller.rb
# frozen_string_literal: true

class Enduser::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/enduser/relationships_controller.rb
class Enduser::RelationshipsController < ApplicationController
  before_action :authenticate_enduser!
  # フォローするとき
  def create
    current_enduser.follow(params[:user_id])
    @enduser = Enduser.find(params[:user_id])
  end
  # フォロー外すとき
  def destroy
    current_enduser.unfollow(params[:user_id])
    @enduser = Enduser.find(params[:user_id])
  end
  # フォロー一覧
  def followings
    enduser = Enduser.find(params[:user_id])
    @endusers = enduser.followings
  end
  # フォロワー一覧
  def followers
    enduser = Enduser.find(params[:user_id])
    @endusers = enduser.followers
  end
  def followingspost
    @posts = Post.where(enduser_id: [*current_enduser.following_ids])
  end
end

app/controllers/enduser/searches_controller.rb
class Enduser::SearchesController < ApplicationController
  before_action :authenticate_enduser!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    @tags = Tag.all

    # 選択したモデルに応じて検索を実行
      if @content.start_with?('#', '＃')
      hashtag = @content[1..-1] # ハッシュタグの#を取り除く
      @records = Post.joins(:hashtags).where(hashtags: { hashname: hashtag })
      @content = hashtag
      @model = 'hashtag'
      @method= 'partial'
      elsif @model == "user"
        @records = Enduser.search_for(@content, @method)
      else
        @records = Post.search_for(@content, @method)
      end
  end
end

app/controllers/enduser/sessions_controller.rb
# frozen_string_literal: true

class Enduser::SessionsController < Devise::SessionsController
  before_action :authenticate_enduser!
  before_action :configure_permitted_parameters, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    enduser = Enduser.guest
    sign_in enduser
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/controllers/enduser/unlocks_controller.rb
# frozen_string_literal: true

class Enduser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/enduser/users_controller.rb
class Enduser::UsersController < ApplicationController
  before_action :authenticate_enduser!
  def show
  @enduser = Enduser.find(params[:id])
  @favorites = @enduser.favorites
  @calendars = @enduser.calendars
  @calendar = Calendar.new

  # Wantlistの処理
  @wantlist = @enduser.wantlist
  @wantlist_parts = @wantlist.present? ? @wantlist.split("\n") : []
  @sorted_wantlist_parts = @wantlist_parts.sort
  @sorted_wantlist = @sorted_wantlist_parts.join("\n")

  # Playlistの処理
  @playlist = @enduser.playlist
  @playlist_parts = @playlist.present? ? @playlist.split("\n") : []
  @sorted_playlist_parts = @playlist_parts.sort_by do |item|
    item.tr('ぁ-ん', 'ァ-ン') # ひらがなをカタカナに変換して比較する
  end
  @sorted_playlist = @sorted_playlist_parts.join("\n")
end

  def new
    @calendar = Calendar.new
  end

  def index
    @users = Enduser.all
    @calendars = Calendar.all
  end

  def create
    Calendar.create(board_params)
    redirect_to boards_path
  end

  def edit
    is_matching_login_enduser
    @enduser = current_enduser # 現在のユーザーを取得するメソッドによって設定
    # @calendar = Calendar.find(params[:id])
  end

  def update
    @enduser = current_enduser # 現在のユーザーを取得するメソッドによって設定
    @calendar = Enduser.find(params[:id])
      if @enduser.update(enduser_params)
      redirect_to user_url(@enduser), notice: 'プロフィールが更新されました。'
      else
        render :edit
      end
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path, notice:"削除しました"
  end

  def confirm_withdrawal
  end

  def withdrawal
  end

  def favorite
  end

  def participant
  end

  def favorite_users
    @favorite_users = current_enduser.favorites.map(&:enduser)
  end


  def is_matching_login_enduser
    enduser = Enduser.find(params[:id])
      unless enduser.id == current_enduser.id
        redirect_to posts_path
      end
  end

  private
  def board_params
    params.require(:board).permit(:title, :content, :start_time)
  end

  def enduser_params
    params.require(:enduser).permit(:name, :bio, :playlist, :wantlist, :profile_picture)
  end
end

app/helpers/admin/endusers_helper.rb
module Admin::EndusersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/enduser/calendars_helper.rb
module Enduser::CalendarsHelper
end

app/views/enduser/homes/about.html.erb
<div id="splash">
<div id="splash-logo">読み込み中</div>
<!--/splash--></div>
<div class="splashbg"></div><!---画面遷移用-->

<div id="container" class="about-page">

  <section class="area area1">
        <div class="content">
          <h2>MurderConnectとは</h2>
          <p>MurderConnectはマーダーミステリーやCOC、TRPGをプレイする人たちが募集を行い繋がるためのサイトです。</p>
        </div>
      </section>

  <section class="area area2">
      <div class="content">
        <h2></h2>
      </div>

      </section>

  <section class="area area3">
        <div class="content">
          <h2>マーダーミステリーとは</h2>
           <p>マーダーミステリー（英語：Murder mystery game）はパーティーゲームの一種である。<br>通常、殺人などの事件が起きたシナリオが用意され、参加者は物語の登場人物となって犯人を探し出したり、犯人役の人は逃げ切る事を目的として会話をしながらゲームを進める。

				それぞれの役柄のバックボーンや事件当日の行動などがシナリオとして用意されており、まさに自分自身が推理小説の世界に入ったような体験ができる。<br>さらに、各シナリオは一度体験するとすべての謎が解けてしまうので一生に一度しかプレイできないことも特徴的。<br>
			</p>
      </section>

  <section class="area area4">
        <div class="content">
          <h2></h2>
      </section>

  <section class="area area5">
        <div class="content">
          <h2>TRPG</h2>
           <p>“TRPG”とは“テーブルトークRPG”の略語で、卓（テーブル）を囲んでトーク（会話）して遊ぶロールプレイングゲーム（RPG）というアナログゲームのジャンルです。<br>
			</p>
      </section>
  <section class="area area6">
        <div class="content">
          <h2></h2>
      </section>
  <section class="area area7">
        <div class="content">
          <h2>COC</h2>
           <p>クトゥルフ神話の原題、『Call of Cthulhu』を略したものになります。<br>
           『クトゥルフ神話TRPG』のことをいい、普通の人々が恐るべきクトゥルフ神話の脅威に立ち向かう、神秘と恐怖のTRPG（テーブルトーク・ロールプレイングゲーム）です。
			</p>
      </section>
  </div>
  <style>

      /*========= ローディング画面のためのCSS ===============*/
#splash {
	position: fixed;
	width: 100%;
	height: 100%;
	background: #333;
	z-index: 9999999;
	text-align:center;
	color:#fff;
}

#splash-logo {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}

/*========= 画面遷移のためのCSS ===============*/

/*画面遷移アニメーション*/
.splashbg{
    display: none;
}

/*bodyにappearクラスがついたら出現*/
body.appear .splashbg{
  /*;*/
    display: block;
    content: "";
    position:fixed;
	z-index: 999;
    width: 100%;
    height: 100vh;
    top: 0;
	left: 0;
    transform: scaleY(0);
    background-color: #333;/*伸びる背景色の設定*/
	animation-name:PageAnime;
	animation-duration:1.2s;
	animation-timing-function:ease-in-out;
	animation-fill-mode:forwards;

}

@keyframes PageAnime{
	0% {
		transform-origin:bottom;
		transform:scaleY(0);
	}
	50% {
		transform-origin:bottom;
		transform:scaleY(1);
	}
	50.001% {
		transform-origin:top;
	}
	100% {
		transform-origin:top;
		transform:scaleY(0);
	}
}

/*画面遷移の後現れるコンテンツ設定*/

#container{
	opacity: 0;/*はじめは透過0に*/
}

/*bodyにappearクラスがついたら出現*/
body.appear #container{
	animation-name:PageAnimeAppear;
	animation-duration:1s;
	animation-delay: 0.8s;
	animation-fill-mode:forwards;
	opacity: 0;
}


@keyframes PageAnimeAppear{
	0% {
	opacity: 0;
	}
	100% {
	opacity: 1;
}
}
.area{
	text-align: center;
}
.area1 {
    background-image: url('path_to_your_image_for_area1.jpg');

    background-position: center; /* 画像の位置を中央に */
}

.area2 {
    background-image: url('path_to_your_image_for_area2.jpg');

    background-position: center;
}
.area1 .content,
.area3 .content,
.area5 .content,
.area7 .content
{
    background-color: rgba(255, 255, 255, 0.7); /* 白色の半透明背景 */
    padding: 20px; /* 必要に応じて調整 */
}
.area2 .content,{

}
    </style>

<script>

$(window).on('load',function(){
$("#splash-logo").delay(1200).fadeOut('slow');//ロゴを1.2秒でフェードアウトする記述

//=====ここからローディングエリア（splashエリア）を1.5秒でフェードアウトした後に動かしたいJSをまとめる
$("#splash").delay(1500).fadeOut('slow',function(){//ローディングエリア（splashエリア）を1.5秒でフェードアウトする記述

$('body').addClass('appear');//フェードアウト後bodyにappearクラス付与

});
//=====ここまでローディングエリア（splashエリア）を1.5秒でフェードアウトした後に動かしたいJSをまとめる

//=====ここから背景が伸びた後に動かしたいJSをまとめたい場合は
$('.splashbg').on('animationend', function() {
//この中に動かしたいJSを記載
});
//=====ここまで背景が伸びた後に動かしたいJSをまとめる

});
</script>

app/views/enduser/homes/top.html.erb
<head>
<meta name="viewport" content="width=device-width,initial-scale=1.0">
  <body>
    <div class="wrapper">
      <h1 class="title">
          <div class="test">Murder Connect</div>
          <a href="<%= new_enduser_session_path %>" class="btn btn-primary mb-3 gradient1 test">ログイン</a>
          <a href="<%= new_enduser_registration_path %>" class="btn btn-success mb-3 gradient1">新規登録</a>
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "btn btn-info gradient1" %><br>
          <%= link_to about_path, class: "btntextchange btn btn-info gradient1" do %>
            <span>About</span>
            <span>サイト概要</span>
          <% end %>
      </h1>
      <ul class="slider">
        <li class="slider-item slider-item01"></li>
        <li class="slider-item slider-item02"></li>
        <li class="slider-item slider-item03"></li>
      </ul>
    <!--/wrapper-->
    <!--<footer class="top">-->
    <!--  <p>&copy; 2023 MurderConnect. All Rights Reserved.</p>-->
    <!--</footer>-->
    </div>

  <style>
    .slider {
        position:relative;
      z-index: 1;
      /*↑z-indexの値をh1のz-indexの値よりも小さくして背景に回す*/
      height: 100vh;/*スライダー全体の縦幅を画面の高さいっぱい（100vh）にする*/
    }
    /*　背景画像設定　*/


    .slider-item {
        width: 100%;/*各スライダー全体の横幅を画面の高さいっぱい（100%）にする*/
        height:100vh;/*各スライダー全体の縦幅を画面の高さいっぱい（100vh）にする*/
        background-repeat: no-repeat;/*背景画像をリピートしない*/
        background-position: center;/*背景画像の位置を中央に*/
        background-size: cover;/*背景画像が.slider-item全体を覆い表示*/
    }

    /*矢印の設定*/

    /*戻る、次へ矢印の位置*/
    .slick-prev,
    .slick-next {
        position: absolute;/*絶対配置にする*/
      z-index: 3;
        top: 42%;
        cursor: pointer;/*マウスカーソルを指マークに*/
        outline: none;/*クリックをしたら出てくる枠線を消す*/
        border-top: 2px solid #ccc;/*矢印の色*/
        border-right: 2px solid #ccc;/*矢印の色*/
        height: 25px;
        width: 25px;
    }

    .slick-prev {/*戻る矢印の位置と形状*/
        left:2.5%;
        transform: rotate(-135deg);
    }

    .slick-next {/*次へ矢印の位置と形状*/
        right:2.5%;
        transform: rotate(45deg);
    }

    /*ドットナビゲーションの設定*/

    .slick-dots {
      position: relative;
      z-index: 3;
        text-align:center;
      margin:-50px 0 0 0;
    }

    .slick-dots li {
        display:inline-block;
      margin:0 5px;
    }

    .slick-dots button {
        color: transparent;
        outline: none;
        width:8px;/*ドットボタンのサイズ*/
        height:8px;/*ドットボタンのサイズ*/
        display:block;
        border-radius:50%;
        background:#ccc;/*ドットボタンの色*/
    }

    .slick-dots .slick-active button{
        background:#333;/*ドットボタンの現在地表示の色*/
    }

    </style>
  </body>
</html>