config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDevise設定
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用のDevise設定
  devise_for :enduser, controllers: {
    registrations: "enduser/registrations",
    sessions: 'enduser/sessions'
  }
  devise_scope :enduser do
  post 'users/guest_sign_in', to: 'enduser/sessions#guest_sign_in'
  end

  scope module: :enduser do
    root to: 'homes#top' # ルートパスを設定
    get 'about' => "homes#about"
    resources :favorite, only: [:create, :destroy]
    get 'users/confirm_withdrawal'
    patch 'users/withdrawal'
    get 'users/participant'
    get '/post/hashtag/:name', to: "posts#hashtag"
    resources :posts do
      resources :participants
    end
    resources :calendars
    resources :users do
      member do
        get 'favorite_users', to: 'users#favorite_users'
      end
      resource :relationships, only: [:show ,:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
          get 'followingspost' => 'relationships#followingspost'
    end
    get "search" => "searches#search"

  end

  namespace :admin do
    root to: 'homes#top'
    get "" => "homes#top"
    resources :posts
    resources :tags#, only: [:index, :create, :edit, :update]
    resources :endusers
  end

end

app/models/posts_helper.rb
module PostsHelper
  def render_with_hashtags(caption)
    caption.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
  end 
end

app/controllers/admin/endusers_controller.rb
class Admin::EndusersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = Enduser.all
  end

  def show
    @enduser = Enduser.find(params[:id])
    @favorites = @enduser.favorites
    @playlist = @enduser.playlist
    @wantlist = @enduser.wantlist
    @calendars = @enduser.calendars
    @calendar = Calendar.new
  end

  def edit
    @enduser = Enduser.find(params[:id])
  end

  def update
    @enduser = Enduser.find(params[:id])
      if @enduser.update(enduser_params)
        redirect_to admin_endusers_path
      else
        render :edit
      end
  end

  private
  def enduser_params
    params.require(:enduser).permit(:name, :bio, :playlist, :wantlist, :is_deleted)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
    def new
      if current_enduser
        @post = current_enduser.posts.new
      else
        redirect_to new_enduser_session_path, alert: "ログインが必要です"
      end
    end

def index
  @tags = Tag.all # タグを取得

  if params[:enduser_id].present?
    @user = Enduser.find(params[:enduser_id])
    # 特定のユーザーに関連する投稿を取得
    @user_posts = @user.posts.includes(:hashtags, :tag)
  else
    # 全ての投稿を取得
    @user_posts = Post.includes(:hashtags, :tag)
  end
end

  def create
    @post = current_enduser.posts.new(post_params)
  
    if @post.save
      redirect_to @post, notice: '投稿が作成されました。'
    else
       @tags = Tag.all
        flash.now[:alert] = '投稿にエラーがあります。'
        render :new # new.html.erbを表示します
    end
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to admin_posts_path, notice: '投稿が削除されました。'
  end

  def show
    @post = Post.find(params[:id])
    @tag = Tag.find(@post.tag_id)
  end
  
  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @posts = @tag.posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :body, :tag_id)
  end
end

app/controllers/enduser/calendars_controller.rb
class Enduser::CalendarsController < ApplicationController

  def index

  end

  def show
    # @calendar = current_enduser.calendars.find(params[:id])
    @calendar = Calendar.find(params[:id])
    pp "@calendar--------------------------#{@calendar.inspect}"
  end

  def new
    @calendars = current_user.calendars
  end

  def edit
    @calendar = current_enduser.calendars.find(params[:id])
  end

  def update

    @calendar = current_enduser.calendars.find(params[:id])
    @calendar.update(update_params)
    redirect_to user_path(current_enduser)
  end

  def create
    @calendar = current_enduser.calendars.new(calendar_memo)
    if @calendar.save
      redirect_to user_path(current_enduser)
    else
      redirect_to new_calendar_path
    end
  end

  def destroy
    @calendars = current_enduser.calendars.find(params[:id])
    @calendars.destroy
    redirect_to user_path(current_enduser)
  end


  private
  def calendar_memo
    params.require(:calendar).permit(:start_time,:title, :content)
  end

  def user
    @user = Enduser.find(params[:id])
  end

  def update_params
    params.require(:calendar).permit(:start_time,:title, :content,:user_id)
  end
end

app/controllers/enduser/confirmations_controller.rb
# frozen_string_literal: true

class Enduser::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_enduser!
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/enduser/favorite_controller.rb
class Enduser::FavoriteController < ApplicationController
  before_action :authenticate_enduser!
  def create
  end

  def destroy
  end
end

app/controllers/enduser/homes_controller.rb
class Enduser::HomesController < ApplicationController
  def top
    @hide_header = true
    render :layout => 'application_top'
  end
  def about
    render :layout => 'application_about'
  end
end

app/controllers/enduser/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Enduser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_enduser!
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/enduser/participants_controller.rb
class Enduser::ParticipantsController < ApplicationController
  before_action :authenticate_access
  def index
    @post = Post.find(params[:post_id])
  end

  def create
    puts "Post ID from params: #{params[:post_id]}"
    @post = Post.find(params[:post_id])
    #byebug
    current_enduser.participate!(@post)
    redirect_to post_participants_path, notice: '参加しました。'
  end

  def destroy
    @post = Post.find(params[:post_id])
    participant = current_enduser.participant_for(@post)
    participant.destroy if participant

    redirect_to post_participants_path, notice: '参加を取り消しました。'
  end

  def show
  end

private
  def authenticate_access
    unless current_admin || current_enduser
      redirect_to new_enduser_session_path, alert: "管理者またはアドミンとしてログインが必要です"
    end
  end
end

app/controllers/enduser/passwords_controller.rb
# frozen_string_literal: true

class Enduser::PasswordsController < Devise::PasswordsController
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/enduser/posts_controller.rb
class Enduser::PostsController < ApplicationController
  before_action :authenticate_enduser!
  def new
    if current_enduser
      @post = current_enduser.posts.new
    else
      redirect_to new_enduser_session_path, alert: "ログインが必要です"
    end
  end

  def index
    @tags = Tag.all # タグを取得

    if params[:enduser_id].present?
      @user = Enduser.find(params[:enduser_id])
      # 特定のユーザーに関連する投稿を取得
      @user_posts = @user.posts.includes(:hashtags, :tag)
    else
      # 全ての投稿を取得
      @user_posts = Post.includes(:hashtags, :tag)
      @posts = Post.all.page(params[:page]).per(4)
    end

  end

  def create
    @post = current_enduser.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: '投稿が作成されました。'
    else
       @tags = Tag.all
        flash.now[:alert] = '投稿にエラーがあります。'
        render :new # new.html.erbを表示します
    end
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path, notice: '投稿が削除されました。'
  end

  def show
    @post = Post.find(params[:id])
    @tag = Tag.find(@post.tag_id)
  end

  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @posts = @tag.posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :body, :tag_id)
  end
end

app/controllers/enduser/registrations_controller.rb
# frozen_string_literal: true

class Enduser::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/enduser/relationships_controller.rb
class Enduser::RelationshipsController < ApplicationController
  before_action :authenticate_enduser!
  # フォローするとき
  def create
    current_enduser.follow(params[:user_id])
    @enduser = Enduser.find(params[:user_id])
  end
  # フォロー外すとき
  def destroy
    current_enduser.unfollow(params[:user_id])
    @enduser = Enduser.find(params[:user_id])
  end
  # フォロー一覧
  def followings
    enduser = Enduser.find(params[:user_id])
    @endusers = enduser.followings
  end
  # フォロワー一覧
  def followers
    enduser = Enduser.find(params[:user_id])
    @endusers = enduser.followers
  end
  def followingspost
    @posts = Post.where(enduser_id: [*current_enduser.following_ids])
  end
end

app/controllers/enduser/searches_controller.rb
class Enduser::SearchesController < ApplicationController
  before_action :authenticate_enduser!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    @tags = Tag.all

    # 選択したモデルに応じて検索を実行
      if @content.start_with?('#', '＃')
      hashtag = @content[1..-1] # ハッシュタグの#を取り除く
      @records = Post.joins(:hashtags).where(hashtags: { hashname: hashtag })
      @content = hashtag
      @model = 'hashtag'
      @method= 'partial'
      elsif @model == "user"
        @records = Enduser.search_for(@content, @method)
      else
        @records = Post.search_for(@content, @method)
      end
  end
end

app/controllers/enduser/sessions_controller.rb
# frozen_string_literal: true

class Enduser::SessionsController < Devise::SessionsController
  before_action :authenticate_enduser!
  before_action :configure_permitted_parameters, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    enduser = Enduser.guest
    sign_in enduser
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/controllers/enduser/unlocks_controller.rb
# frozen_string_literal: true

class Enduser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/enduser/users_controller.rb
class Enduser::UsersController < ApplicationController
  before_action :authenticate_enduser!
  def show
  @enduser = Enduser.find(params[:id])
  @favorites = @enduser.favorites
  @calendars = @enduser.calendars
  @calendar = Calendar.new

  # Wantlistの処理
  @wantlist = @enduser.wantlist
  @wantlist_parts = @wantlist.present? ? @wantlist.split("\n") : []
  @sorted_wantlist_parts = @wantlist_parts.sort
  @sorted_wantlist = @sorted_wantlist_parts.join("\n")

  # Playlistの処理
  @playlist = @enduser.playlist
  @playlist_parts = @playlist.present? ? @playlist.split("\n") : []
  @sorted_playlist_parts = @playlist_parts.sort_by do |item|
    item.tr('ぁ-ん', 'ァ-ン') # ひらがなをカタカナに変換して比較する
  end
  @sorted_playlist = @sorted_playlist_parts.join("\n")
end

  def new
    @calendar = Calendar.new
  end

  def index
    @users = Enduser.all
    @calendars = Calendar.all
  end

  def create
    Calendar.create(board_params)
    redirect_to boards_path
  end

  def edit
    is_matching_login_enduser
    @enduser = current_enduser # 現在のユーザーを取得するメソッドによって設定
    # @calendar = Calendar.find(params[:id])
  end

  def update
    @enduser = current_enduser # 現在のユーザーを取得するメソッドによって設定
    @calendar = Enduser.find(params[:id])
      if @enduser.update(enduser_params)
      redirect_to user_url(@enduser), notice: 'プロフィールが更新されました。'
      else
        render :edit
      end
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path, notice:"削除しました"
  end

  def confirm_withdrawal
  end

  def withdrawal
  end

  def favorite
  end

  def participant
  end

  def favorite_users
    @favorite_users = current_enduser.favorites.map(&:enduser)
  end


  def is_matching_login_enduser
    enduser = Enduser.find(params[:id])
      unless enduser.id == current_enduser.id
        redirect_to posts_path
      end
  end

  private
  def board_params
    params.require(:board).permit(:title, :content, :start_time)
  end

  def enduser_params
    params.require(:enduser).permit(:name, :bio, :playlist, :wantlist, :profile_picture)
  end
end

app/helpers/admin/endusers_helper.rb
module Admin::EndusersHelper
end

app/views/enduser/posts/_post.html.erb
<div class="wrapper">
  <ul class="article-list">
    <li>
      <%= link_to post.title, current_user.is_a?(Admin) ? admin_post_path(post) : post %><br>
      <p>投稿者名: <%= link_to post.enduser.name, user_path(post.enduser) %></p>
      <%= post.body %>
      <% post.hashtags.each do |hashtag| %>
        <%= link_to "##{hashtag.hashname}", search_path(content: "##{hashtag.hashname}", model: "post", method: "perfect") %>
      <% end %>
      タグ: <%= post.tag.tag_title %>
    </li>
  </ul>
</div>

app/views/enduser/posts/_post_card.html.erb
<% tags.each do |tag| %>
  <div id="<%= tag.tag_title %>" class="area">
    <div class="row">
      <% user_posts.where(tag_id: tag.id).each do |post| %>
        <div class="col-md-3">
          <div class="card" style="width: 100%; height: 400px; margin: 10px;">
            <%= link_to (current_admin ? admin_post_path(post) : post) do %>
              <% if post.og_image.present? %>
                <%= image_tag post.og_image, class: "fixed-size-image" %>
              <% else %>
                <%= image_tag "noimage.png", class: "fixed-size-image" %>
              <% end %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to post.title, (current_admin ? admin_post_path(post) : post) %></h5>
              <p class="card-text">投稿者名: <%= link_to post.enduser.name, user_path(post.enduser) %></p>
              <% clean_body = post.body.gsub(/\n/, ' ') %>
              <a class="poster" data-poster="<%= truncate(clean_body, length: 70, separator: ' ', omission: '...') %>">
                <%= truncate(clean_body, length: 70, separator: ' ', omission: '...') %>
              </a>
              <span class="full-text" style="display:none;"><%= simple_format(post.body) %></span>
              <a class="show-more-link">詳細を見る</a>
              <a class="show-less-link" style="display:none;">元に戻す</a>
              ハッシュタグ:<% post.hashtags.limit(3).each do |hashtag| %>
                <%= link_to "##{hashtag.hashname}", search_path(content: "##{hashtag.hashname}", model: "post", method: "perfect") %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
		</div>
  </div>
<% end %>

<style>/*tabの形状*/
.show-more-link,
.show-less-link {
  color: #007bff !important;
  font-size: 14px; /* フォントサイズ */
}
.fixed-size-image {
  width: 100%; /* 例: 幅を300ピクセルに指定 */
  height: 170px; /* 例: 高さを200ピクセルに指定 */
  object-fit: cover; /* 画像を親要素にフィットさせる */
}

.card-body {

}

.tab{
	display: flex;
	flex-wrap: wrap;
}
.tab li a{
	display: block;
	background:#ddd;
	margin:0 2px;
	padding:10px 20px;
}
/*liにactiveクラスがついた時の形状*/
.tab li.active a{
	background:#fff;
}


/*エリアの表示非表示と形状*/
.area {
	display: none;/*はじめは非表示*/
	opacity: 0;/*透過0*/
	padding:20px 20px;
}

/*areaにis-activeというクラスがついた時の形状*/
.area.is-active {
    display: block;/*表示*/
    animation-name: displayAnime;/*ふわっと表示させるためのアニメーション*/
    animation-duration: 2s;
    animation-fill-mode: forwards;
}

@keyframes displayAnime{
	from {
		opacity: 0;
	}
	to {
		opacity: 1;
	}
}
</style>
<script>
  //任意のタブにURLからリンクするための設定
function GethashID (hashIDName){
	if(hashIDName){
		//タブ設定
		$('.tab li').find('a').each(function() { //タブ内のaタグ全てを取得
			var idName = $(this).attr('href'); //タブ内のaタグのリンク名（例）#lunchの値を取得
			if(idName == hashIDName){ //リンク元の指定されたURLのハッシュタグ（例）http://example.com/#lunch←この#の値とタブ内のリンク名（例）#lunchが同じかをチェック
				var parentElm = $(this).parent(); //タブ内のaタグの親要素（li）を取得
				$('.tab li').removeClass("active"); //タブ内のliについているactiveクラスを取り除き
				$(parentElm).addClass("active"); //リンク元の指定されたURLのハッシュタグとタブ内のリンク名が同じであれば、liにactiveクラスを追加
				//表示させるエリア設定
				$(".area").removeClass("is-active"); //もともとついているis-activeクラスを取り除き
				$(hashIDName).addClass("is-active"); //表示させたいエリアのタブリンク名をクリックしたら、表示エリアにis-activeクラスを追加
			}
		});
	}
}

//タブをクリックしたら
$('.tab a').on('click', function() {
	var idName = $(this).attr('href'); //タブ内のリンク名を取得
	GethashID (idName);//設定したタブの読み込みと
	return false;//aタグを無効にする
});

$(document).ready(function(){
  GethashID("#PL"); // #PL タブを表示する
});
// 上記の動きをページが読み込まれたらすぐに動かす
$(window).on('load', function () {
    var hashName = "#PL"; // ランチのタブを表示したい場合
    GethashID (hashName);
});


document.addEventListener('DOMContentLoaded', function() {
  var showMoreLinks = document.querySelectorAll('.show-more-link');
  var showLessLinks = document.querySelectorAll('.show-less-link');

  showMoreLinks.forEach(function(link) {
    link.addEventListener('click', function() {
      var fullTextElement = this.previousElementSibling; // 詳細の全文要素を取得
      var showLessLink = this.nextElementSibling; // 元に戻すリンクを取得
      var truncatedTextElement = this.parentElement.querySelector('.poster'); // 70文字以上の要素を取得

      truncatedTextElement.style.display = 'none'; // 70文字以内の要素を非表示にする
      fullTextElement.style.display = 'inline'; // 全文を表示
      this.style.display = 'none'; // 詳細を見るリンクを非表示
      showLessLink.style.display = 'inline'; // 元に戻すリンクを表示

      var fullText = fullTextElement.innerHTML;
      fullText = fullText.replace(/<br>/g, ''); // 全ての<br>タグを削除
      fullTextElement.innerHTML = fullText;
    });
  });

showLessLinks.forEach(function(link) {
  link.addEventListener('click', function() {
    var fullTextElement = this.previousElementSibling.previousElementSibling;
    var showMoreLink = this.previousElementSibling;
    var truncatedTextElement = this.parentElement.querySelector('.poster');
    var card = this.closest('.card'); // カード要素を取得

    truncatedTextElement.innerHTML = truncatedTextElement.dataset.poster; // HTMLを元に戻す
    truncatedTextElement.style.display = 'inline';
    fullTextElement.style.display = 'none';
    showMoreLink.style.display = 'inline';
    this.style.display = 'none';

    card.style.height = '400px'; // カードの高さを400pxに戻す
  });
});

  var cards = document.querySelectorAll('.card');

  showMoreLinks.forEach(function(link, index) {
    link.addEventListener('click', function() {
      var card = cards[index];
      card.style.height = 'auto';
    });
  });

  // 詳細が70文字以内の場合に詳細を見るボタンと元に戻すボタンを非表示にする
  var posters = document.querySelectorAll('.poster');
  var full_texts = document.querySelectorAll('.full-text');
  full_texts.forEach(function(full_text) {
    console.log(full_text.innerText)
    console.log(full_text.innerText.length)
    if (full_text.innerText.length < 71) {
      var showMoreLink = full_text.nextElementSibling;
      var showLessLink = showMoreLink.nextElementSibling;

      showMoreLink.style.display = 'none';
      showLessLink.style.display = 'none';
    }
  });
});


</script>

app/views/enduser/posts/_posts.html.erb
<% if posts.present? && posts.any? %>
  <% posts.each do |post| %>
    <%= render 'enduser/posts/post', {post: post} %>
  <% end %>
  <% else %>
  <p>まだ投稿がありません。</p>
<% end %>

app/views/enduser/posts/hashtag.html.erb
<h2>ハッシュタグ #<%= @tag.hashname %></h2>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to posts_path(post.id) do %>
          
        <% end %>
      </li>
    <% end %>
  </ul>

app/views/enduser/posts/index.html.erb
<!-- タブの生成 -->
<ul class="tab" id="tagTabs">
  <% @tags.each do |tag| %>
    <li><a href="#<%= tag.tag_title %>"><%= tag.tag_title %></a></li>
  <% end %>
</ul>


<%= render partial: "post_card", locals: { tags: @tags, user_posts: @user_posts } %>

   <%= link_to "新しい投稿", new_post_path, class: "btn btn-primary btn-lg new_button" %>
   
<%= paginate @posts %>

app/views/enduser/posts/new.html.erb
<div class="container mt-4">
  <%= form_for(@post, url: posts_path, html: {class: "card p-4"}) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'タイトルを入力してください' %>
    </div>

    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', placeholder: 'URLを入力してください' %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', rows: 5, placeholder: '本文を入力してください' %>
    </div>

    <div class="form-group">
      <%= f.label :tag_id %>
      <%= f.select :tag_id, Tag.all.map { |tag| [tag.tag_title, tag.id] }, {}, class: 'form-control' %>
    </div>

    <%= f.submit "投稿", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/enduser/posts/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-3">
          <%= image_tag @post.og_image, class: "card-img-top", width: "200", height: "200" if @post.og_image.present? %>
        </div>

        <div class="col-9">
          <h2 class="card-title"><%= @post.title %></h2>
          <p class="card-text">作品ページ: <a href="<%= @post.url %>" target="_blank"><%= @post.url %></a></p>
          <p class="card-text">Body: <%= simple_format(@post.body) %></p>
          <h5 class="card-subtitle mb-2 text-muted mt-3">ハッシュタグ</h5>
          <% @post.hashtags.each do |hashtag| %>
            <%= link_to "##{hashtag.hashname}", search_path(content: "#{hashtag.hashname}", model: "post", method: "perfect"), class: "badge badge-primary mr-2" %>
          <% end %>
          <div class="mt-4">
            <% unless @post.enduser == current_enduser %>
              <% if @post.participanted_by?(current_enduser) %>
                <%= link_to '参加取り消し', post_participant_path(@post, current_enduser.participant_for(@post)), method: :delete, class: 'btn btn-danger' %>
              <% else %>
                <%= link_to '参加する', post_participants_path(@post), method: :post, class: 'btn btn-primary' %>
              <% end %>
            <% end %>
          </div>

          <%= link_to '参加者一覧', post_participants_path(@post), class: 'btn btn-primary mt-3' %>

          <% if current_enduser && @post.enduser_id == current_enduser.id || current_admin %>
            <%= link_to '投稿を削除', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger mt-3' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>