config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDevise設定
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用のDevise設定
  devise_for :enduser, controllers: {
    registrations: "enduser/registrations",
    sessions: 'enduser/sessions'
  }
  devise_scope :enduser do
  post 'users/guest_sign_in', to: 'enduser/sessions#guest_sign_in'
  end

  scope module: :enduser do
    root to: 'homes#top' # ルートパスを設定
    get 'about' => "homes#about"
    resources :favorite, only: [:create, :destroy]
    get 'users/confirm_withdrawal'
    patch 'users/withdrawal'
    get 'users/participant'
    get '/post/hashtag/:name', to: "posts#hashtag"
    resources :posts do
      resources :participants
    end
    resources :calendars
    resources :users do
      member do
        get 'favorite_users', to: 'users#favorite_users'
      end
      resource :relationships, only: [:show ,:create, :destroy]
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'followers' => 'relationships#followers', as: 'followers'
          get 'followingspost' => 'relationships#followingspost'
    end
    get "search" => "searches#search"

  end

  namespace :admin do
    root to: 'homes#top'
    get "" => "homes#top"
    resources :posts
    resources :tags#, only: [:index, :create, :edit, :update]
    resources :endusers
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_one_attached :profile_picture
  has_many :followings, -> { where(is_deleted: false) }, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, -> { where(is_deleted: false) }, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :posts, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :calendars, dependent: :destroy
  attr_accessor :custom_playlist_name
  attr_accessor :custom_wantlist_name

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :encrypted_password, presence: true, length: { minimum: 6 }, confirmation: true

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |enduser|
      enduser.password = SecureRandom.urlsafe_base64
      enduser.name = 'Guest User'  # デフォルトの名前を設定
      # 他のゲストユーザーの属性をここに追加する
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def participate!(post)
    participants.create(post: post)
  end

  def participant_for(post)
    participants.find_by(post_id: post.id)
  end

  def guest?
  name == "Guest User"
  end

  def self.search_for(content, method)
      Enduser.where('name LIKE ?', '%' + content + '%')
  end

     # フォローしたときの処理
  def follow(enduser_id)
    relationships.create(followed_id: enduser_id)
  end
  # フォローを外すときの処理
  def unfollow(enduser_id)
    relationships.find_by(followed_id: enduser_id).destroy
  end
  # フォローしているか判定
  def following?(enduser)
    followings.include?(enduser)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :enduser
  belongs_to :post
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: { maximum: 99 }
  has_many :post_hashtag_relations
  has_many :posts, through: :post_hashtag_relations
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :enduser
  belongs_to :post
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :participants, dependent: :destroy
  belongs_to :enduser
  belongs_to :tag
  has_many :post_hashtag_relations , dependent: :destroy
  has_many :hashtags, through: :post_hashtag_relations, dependent: :destroy
  has_one_attached :thumbnail
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp }
  validates :body, presence: true
  validates :tag_id, presence: true

  def self.search_for(content, method)
      Post.where('title LIKE ?', '%' + content + '%')
  end

  def participanted_by?(enduser)
    participants.exists?(enduser_id: enduser.id)
  end
  def caption
    # ここで投稿のキャプション（例: 本文やタイトル）を返すコードを書く
    return self.body
  end

    after_create do
      hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      self.body = self.body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/, '') # ハッシュタグを除去
      self.save
      self.hashtags = [] # ハッシュタグの関連をクリア
      unique_hashtags = hashtags.uniq.map { |hashtag| hashtag.downcase.delete('#＃') }
      hashtags.uniq.map do |hashtag|
        tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#＃'))
        self.hashtags << tag
      end
    end

    before_update do
      post = Post.find_by(id: self.id)
      post.hashtags.clear
      hashtags = self.caption.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.uniq.map do |hashtag|
        tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
        post.hashtags << tag
      end
    end
    
    def og_image
      og = OpenGraph.new(self.url)
      # og.title # => "Open Graph protocol"
      # og.type # => "website"
      # og.url # => "http://ogp.me/"
      # og.description # => "The Open Graph protocol enables any web page to become a rich object in a social graph."
      return og.images[0] # => ["http://ogp.me/logo.png"]
    end 
    def og_title
      og = OpenGraph.new(self.url)
      # og.title # => "Open Graph protocol"
      # og.type # => "website"
      # og.url # => "http://ogp.me/"
      # og.description # => "The Open Graph protocol enables any web page to become a rich object in a social graph."
      return og.title # => ["http://ogp.me/logo.png"]
    end
end

app/models/post_hashtag_relation.rb
class PostHashtagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :hashtag
  with_options presence: true do
    validates :post_id
    validates :hashtag_id
  end
end

app/models/posts_helper.rb
module PostsHelper
  def render_with_hashtags(caption)
    caption.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
  end 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Enduser"
  belongs_to :followed, class_name: "Enduser"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :tag_title, presence: true
end

app/models/wantlist.rb
class Wantlist < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def after_sign_in_path_for(resource)
    user_path(current_enduser)
  end

  def after_sign_up_path_for(resource)
    user_path(current_enduser)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enduser/homes_helper.rb
module Enduser::HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MurderConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--タブ切り替え用のCSS-->
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!---------------------------------->
    <script src="https://kit.fontawesome.com/b4a254db2e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body>
    <% if !@hide_header %>
    <header class="navbar navbar-expand-lg header">

      <div class="collapse navbar-collapse" id="navbarNav">
        <%= link_to root_path do %>
          <%= image_tag("logo.jpg", alt: "MyLogo",style: "height: 40px;") %>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <% if current_enduser %>
            <li class="nav-item">
              <%= link_to "会員一覧", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_enduser), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_enduser_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% elsif current_admin %>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_endusers_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ一覧", admin_tags_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
  <div><%= render "/enduser/searches/form" %></div>
      <% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

  <% if flash[:errors] %>
    <ul class="errors">
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>
<%= yield %>
<footer>
  <p>&copy; 2023 MurderConnect. All Rights Reserved.</p>
</footer>
  </body>

</html>

app/views/layouts/application_about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MurderConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--タブ切り替え用のCSS-->
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!---------------------------------->
    <script src="https://kit.fontawesome.com/b4a254db2e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body class = "image">
    <% if !@hide_header %>
    <header class="navbar navbar-expand-lg header">

      <div class="collapse navbar-collapse" id="navbarNav">
        <%= link_to root_path do %>
          <%= image_tag("logo.jpg", alt: "MyLogo",style: "height: 40px;") %>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <% if current_enduser %>
            <li class="nav-item">
              <%= link_to "会員一覧", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_enduser), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_enduser_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% elsif current_admin %>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_endusers_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ一覧", admin_tags_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
  <div><%= render "/enduser/searches/form" %></div>
      <% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

  <% if flash[:errors] %>
    <ul class="errors">
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>
<%= yield %>
<footer>
  <p>&copy; 2023 MurderConnect. All Rights Reserved.</p>
</footer>
  </body>

</html>

app/views/layouts/application_top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MurderConnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--タブ切り替え用のCSS-->
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!---------------------------------->
    <script src="https://kit.fontawesome.com/b4a254db2e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body class = "about">
    <% if !@hide_header %>
    <header class="navbar navbar-expand-lg header">
      <a class="navbar-brand" href="<%= root_path %>">MyLogo</a>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if current_enduser %>
            <li class="nav-item">
              <%= link_to "会員一覧", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_enduser), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_enduser_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% elsif current_admin %>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_endusers_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ一覧", admin_tags_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
  <div><%= render "/enduser/searches/form" %></div>
      <% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

  <% if flash[:errors] %>
    <ul class="errors">
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>
<%= yield %>
<footer class="top">
  <p>&copy; 2023 MurderConnect. All Rights Reserved.</p>
</footer>
  </body>

</html>